### ISSUE TITLE
New Testing Device: Mi 9T / LineageOS 21

### ISSUE THREAD

**Issue by MW-SAND** [Isaaker/Spotify-AdsList#13]
### Platform

App

### Device

Mi 9T

### OS & Version

LineageOS 21

### Browser & Version (If applicable)

Spotify App

### Testing Date

26-06-2024

### Status

ERROR

### List Type

Pi-hole

### Extra Info about the testing

Music interrupting ads are still played.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I read the avaible Documentation
- [X] I have checked that there is no issue on the same subject
- [X] I have checked that my issue does not contain any relevant security data (Passwords, Secrets or Users)
- [X] I have checked that my issue is not a Security Vulneability [Security Policy](https://github.com/Isaaker/Ghost_Simulator_ES/blob/main/SECURITY.md)

**Comment by Isaaker** [comment]
Hi, thanks for the report.

I will investigate the problem and look for domains that have not been blocked.

In the meantime, I will add the device to the README as non-functional.

**Comment by MW-SAND** [comment]
Thank you very much, please let me know if you need any additional information.

**Comment by Isaaker** [comment]
Hi again, I've been working hard for a few days on various reports about ads that keep showing up on Spotify. However, although I have found some domains unnecessarily unblocked, I still can't identify which domains are giving the problem, as they work fine for me.

If you could send me some logs of the domains your adblocker is receiving traffic from (blocked and not) so I can detect the domains that should be blocked this would help me. Because sometimes, some domains and requests may depend on the country, region or computer configuration (OS, app/web...).

If you want, you can also send me this information privately so it is not shown here, to my email: isaaker.hernan@proton.me

**Comment by Isaaker** [comment]
I have fixed the problem with the ads in the last PR. Please confirm that you are no longer shown ads.

🙂 Thank you
