### ISSUE TITLE
[BUG]: The ads are still there

### ISSUE THREAD

**Issue by AlkBek** [Isaaker/Spotify-AdsList#14]
### What happened?

A bug happened! I have ublock origin, the ads still remain. I would also like to know how to add this whitelist to ublock origin. I would also like the name of the filter to be if you import it, and not the link

### Browser

Chrome

### Browser Version

Version 126.0.6478.127 (64 bits)

### Operative System (OS)

Windows (Microsoft)

### OS Version

22H2 19045.4170

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I read the avaible Documentation
- [X] I have checked that there is no issue on the same subject
- [X] I have checked that my issue does not contain any relevant security data (Passwords, Secrets or Users)
- [X] I have checked that my issue is not a Security Vulneability [Security Policy](https://github.com/Isaaker/Ghost_Simulator_ES/blob/main/SECURITY.md)

**Comment by Isaaker** [comment]
Hi @AlkBek, thanks for your report!

I am not very familiar with the syntactic structure of ublock origin, so the list was not currently available for this blocker. However, I will try to create a new version of SpotifyAds List for ublock origin.

As for the problem of still showing ads, I am investigating the problem that has already been reported to me in #12 and #13.

To add a whitelist to ublock origin, you can follow the steps detailed in this support article.

While the issue is being fixed add the bug to our README.

**Comment by Isaaker** [comment]
Hi again, I've been working hard for a few days on various reports about ads that keep showing up on Spotify. However, although I have found some domains unnecessarily unblocked, I still can't identify which domains are giving the problem, as they work fine for me.

If you could send me some logs of the domains your adblocker is receiving traffic from (blocked and not) so I can detect the domains that should be blocked this would help me. Because sometimes, some domains and requests may depend on the country, region or computer configuration (OS, app/web...).

If you want, you can also send me this information privately so it is not shown here, to my email: isaaker.hernan@proton.me

**Comment by Isaaker** [comment]
I have fixed the problem with the ads in the last PR. Please confirm that you are no longer shown ads.

🙂 Thank you
