### ISSUE TITLE
[Q] Can I ask why some lines are duplicates of existing domains but without the tld?

### ISSUE THREAD

**Issue by vavavr00m** [Isaaker/Spotify-AdsList#7]
### Write here your issue

```
adclick.g.doublecklick.
ads-fa.spotify.ads.pubmatic.c
analytics.spotify.
content.bitsontherun.
core.insightexpressai.
d2gi7ultltnc2u.cloudfront.
d3rt1990lpmkn.cloudfront.
ds.serving-sys.gads.pubmatic.c
googleads.g.doubleclick.
gtssl2-ocsp.geotrust.
labs.spotify.community
js.moatads.
log.spotify.
bounceexchange.
bs.serving-sys.
pagead2.googlesyndication.
pagead46.l.doubleclick.
partner.googleadservices.
tpc.googlesyndication.
v.jwpcdn.
video-ad-stats.googlesyndication.
www.googleadservices.
www.googletagservices.
```

![image](https://github.com/Isaaker/Spotify-AdsList/assets/4675132/f3d0c6c8-d30a-400d-9320-de35397a45a9)

### Code of Conduct

- [X] I select a issue Label, on the rigth menu bar
- [X] I agree to follow this project's Code of Conduct
- [X] I read the avaible Documentation
- [X] I have checked that there is no issue on the same subject
- [X] I have checked that my issue does not contain any relevant security data (Passwords, Secrets or Users)
- [X] I have checked that my issue is not a Security Vulneability [Security Policy](https://github.com/Isaaker/Ghost_Simulator_ES/blob/main/SECURITY.md)

**Comment by Isaaker** [comment]
Hi @vavavr00m, thank you for participating in the repository.

I think I made a mistake during some of the domain conversions and that's why those domains were like that, because as you can see some of them have "domain.c" and what happened is that the "om" of ".com" was deleted.

I will fix this as soon as possible so that no alerts are shown and I will also try to make some actions to automate the conversion so these errors do not occur again.

🙂Thank you again for contributing to the repository.

**Comment by Isaaker** [comment]
Okay, thanks 🙂.
